import { defineConfig } from '@playwright/test'

// Journey specs generated by agent-handles (npx agent-handles journeys
// compile). Run with: npx playwright test
const port = Number(process.env.PORT) || 5199

export default defineConfig({
  testDir: 'tests',
  use: {
    baseURL: `http://localhost:${port}`,
    testIdAttribute: 'data-testid',
  },
  webServer: {
    command: `npm run dev -- --port ${port} --strictPort`,
    url: `http://localhost:${port}`,
    reuseExistingServer: true,
    stdout: 'ignore',
  },
})
