// Generated by agent-handles from agent-handles/journey/v1 journeys. Do not edit;
// edit the journey manifest and recompile (npx agent-handles journeys compile).
import { test, expect } from "@playwright/test";

test("backtest-advanced-disclosure: The backtest builder's Advanced toggle is present and enabled. (Click intentionally omitted: the ticker picker autofocuses on load and its open dropdown overlays the toggle; v1 journeys cannot reference the dropdown's dynamic option ids to dismiss it first.)", async ({ page }) => {
  await page.goto("/backtest");
  await expect(page.getByTestId("backtest.builder.advanced-toggle")).toBeVisible({ timeout: 10000 });
  await expect(page.getByTestId("backtest.builder.advanced-toggle")).toBeEnabled();
});

test("allocation-advanced-disclosure: The allocation builder's Advanced section is reachable through its stable id.", async ({ page }) => {
  await page.goto("/allocation");
  await expect(page.getByTestId("allocation.builder.advanced-toggle")).toBeVisible({ timeout: 10000 });
  await page.getByTestId("allocation.builder.advanced-toggle").click();
});

test("xray-positions-entry: Portfolio X-ray accepts pasted positions through the identified inputs.", async ({ page }) => {
  await page.goto("/xray");
  await expect(page.getByTestId("xray.inputs.positions")).toBeVisible({ timeout: 10000 });
  await page.getByTestId("xray.inputs.positions").fill("AAPL 12\nVTI 40");
  await expect(page.getByTestId("xray.inputs.positions")).toBeEnabled();
});
