// Generated by agent-handles from agent-handles/journey/v1 journeys. Do not edit;
// edit the journey manifest and recompile (npx agent-handles journeys compile).
import { test, expect } from "@playwright/test";

test("backtest-advanced-disclosure: The backtest builder's Advanced toggle is present and enabled.", async ({ page }) => {
  await page.goto("/backtest");
  await expect(page.getByTestId("backtest.builder.advanced-toggle")).toBeVisible({ timeout: 10000 });
  await expect(page.getByTestId("backtest.builder.advanced-toggle")).toBeEnabled();
});

test("allocation-advanced-disclosure: The allocation builder's Advanced section is reachable through its stable id.", async ({ page }) => {
  await page.goto("/allocation");
  await expect(page.getByTestId("allocation.builder.advanced-toggle")).toBeVisible({ timeout: 10000 });
  await page.getByTestId("allocation.builder.advanced-toggle").click();
});

test("xray-positions-entry: Portfolio X-ray accepts pasted positions through the identified inputs.", async ({ page }) => {
  await page.goto("/xray");
  await expect(page.getByTestId("xray.inputs.positions")).toBeVisible({ timeout: 10000 });
  await page.getByTestId("xray.inputs.positions").fill("AAPL 12\nVTI 40");
  await expect(page.getByTestId("xray.inputs.positions")).toBeEnabled();
});

test("backtest-builder-control-path: Build AMZN/GOOGL 60/40 vs SPY/QQQ through the controls alone: letter-by-letter ticker entry, keyboard selection, weight edits, the Radix rebalance dropdown, and the reinvest switch, ending with results rendered. Recorded live 2026-08-25 (27/27 receipts ok); the predicate v2 acceptance journey.", async ({ page }) => {
  await page.goto("/");
  await page.getByTestId("app.nav.backtest").click();
  await page.getByTestId("backtest.builder.picker-p1").pressSequentially("AMZN");
  await page.getByTestId("backtest.builder.picker-p1").press("Enter");
  await page.getByTestId("backtest.builder.picker-p1").pressSequentially("GOOGL");
  await page.getByTestId("backtest.builder.picker-p1").press("Enter");
  await page.getByTestId("backtest.builder.weight-p1-AMZN").fill("60");
  await page.getByTestId("backtest.builder.weight-p1-GOOGL").fill("40");
  await page.getByTestId("backtest.builder.add-portfolio").click();
  await page.getByTestId("backtest.builder.picker-p2").pressSequentially("SPY");
  await page.getByTestId("backtest.builder.picker-p2").press("Enter");
  await page.getByTestId("backtest.builder.picker-p2").pressSequentially("QQQ");
  await page.getByTestId("backtest.builder.picker-p2").press("Enter");
  await expect(page.getByTestId("backtest.results.export-csv")).toBeVisible({ timeout: 20000 });
  await page.getByTestId("backtest.builder.advanced-toggle").click();
  await page.getByTestId("backtest.builder.rebalance-trigger").click();
  await page.getByTestId("backtest.builder.rebalance-quarterly").click();
  await expect(page.getByTestId("backtest.builder.rebalance-trigger")).toContainText("Quarterly", { timeout: 5000 });
  await expect(page.getByTestId("backtest.builder.reinvest-toggle")).toBeChecked();
  await page.getByTestId("backtest.builder.reinvest-toggle").click();
  await expect(page.getByTestId("backtest.builder.reinvest-toggle")).not.toBeChecked({ timeout: 5000 });
  await page.getByTestId("backtest.builder.reinvest-toggle").click();
  await expect(page.getByTestId("backtest.builder.reinvest-toggle")).toBeChecked({ timeout: 5000 });
  await expect(page.getByTestId("backtest.results.export-csv")).toBeVisible({ timeout: 20000 });
});

test("research-ticker-drill: Nav to Research, find TXRH letter by letter, open it, then switch to AAPL through the header control. Recorded live 2026-08-25 (10/10 receipts ok), the first zero-navigate journey.", async ({ page }) => {
  await page.goto("/");
  await page.getByTestId("app.nav.stock").click();
  await page.getByTestId("ui.ticker-picker.search").pressSequentially("TXRH");
  await expect(page.getByTestId("ui.ticker-picker.option-TXRH")).toBeVisible({ timeout: 5000 });
  await page.getByTestId("ui.ticker-picker.option-TXRH").click();
  await expect(page.getByTestId("stock.header.switch-ticker")).toBeVisible({ timeout: 20000 });
  await expect(page.getByTestId("stock.header.switch-ticker")).toContainText("TXRH");
  await page.getByTestId("stock.header.switch-ticker").click();
  await page.getByTestId("ui.ticker-picker.search").pressSequentially("AAPL");
  await expect(page.getByTestId("ui.ticker-picker.option-AAPL")).toBeVisible({ timeout: 5000 });
  await page.getByTestId("ui.ticker-picker.option-AAPL").click();
  await expect(page.getByTestId("stock.header.switch-ticker")).toContainText("AAPL", { timeout: 20000 });
});

test("landing-cards: The landing page's tool cards are real entrances: the Monte Carlo card lands on the plan inputs.", async ({ page }) => {
  await page.goto("/");
  await expect(page.getByTestId("landing.tools.card-backtest")).toBeVisible({ timeout: 10000 });
  await page.getByTestId("landing.tools.card-montecarlo").click();
  await expect(page.getByTestId("montecarlo.plan.starting-balance")).toBeVisible({ timeout: 10000 });
});

test("montecarlo-plan-control-path: Retirement plan edited through the controls: balance, horizon, and the simulation method dropdown.", async ({ page }) => {
  await page.goto("/");
  await page.getByTestId("app.nav.montecarlo").click();
  await page.getByTestId("montecarlo.plan.starting-balance").fill("750000");
  await page.getByTestId("montecarlo.plan.years-to-retire").fill("10");
  await page.getByTestId("montecarlo.plan.horizon").fill("40");
  await page.getByTestId("montecarlo.plan.method-trigger").click();
  await page.getByTestId("montecarlo.plan.method-bootstrap").click();
  await expect(page.getByTestId("montecarlo.plan.method-trigger")).toContainText("Bootstrap", { timeout: 5000 });
});

test("allocation-builder-control-path: Allocation built through the controls: asset picked from the autocomplete, weights edited, a comparison portfolio added, dates set through the date picker, inflation toggled.", async ({ page }) => {
  await page.goto("/");
  await page.getByTestId("app.nav.allocation").click();
  await page.getByTestId("allocation.builder.picker-p1").pressSequentially("small");
  await expect(page.getByTestId("allocation.asset-picker.option-smallCap")).toBeVisible({ timeout: 5000 });
  await page.getByTestId("allocation.asset-picker.option-smallCap").click();
  await expect(page.getByTestId("allocation.builder.weight-p1-smallCap")).toBeVisible({ timeout: 10000 });
  await page.getByTestId("allocation.builder.add-portfolio").click();
  await page.getByTestId("ui.date-picker.input-alloc-start").fill("01/01/1990");
  await expect(page.getByTestId("ui.date-picker.clear-alloc-start")).toBeVisible({ timeout: 5000 });
  await page.getByTestId("allocation.builder.inflation-toggle").click();
  await expect(page.getByTestId("allocation.builder.inflation-toggle")).toBeChecked({ timeout: 5000 });
});

test("income-sample-portfolio: The dividend planner's one-tap sample loads SCHD/VYM/JEPI; total value and per-holding weights stay editable.", async ({ page }) => {
  await page.goto("/");
  await page.getByTestId("app.nav.income").click();
  await page.getByTestId("income.setup.load-sample").click();
  await expect(page.getByTestId("income.setup.weight-SCHD")).toBeVisible({ timeout: 20000 });
  await page.getByTestId("income.setup.total-value").fill("250000");
  await page.getByTestId("income.setup.weight-SCHD").fill("50");
  await expect(page.getByTestId("income.setup.weight-JEPI")).toBeVisible();
});

test("stock-to-backtest-crossover: Cross-page control path: research AAPL, then the stock header's Backtest button seeds the backtest builder with AAPL at 100.", async ({ page }) => {
  await page.goto("/");
  await page.getByTestId("app.nav.stock").click();
  await page.getByTestId("ui.ticker-picker.search").pressSequentially("AAPL");
  await expect(page.getByTestId("ui.ticker-picker.option-AAPL")).toBeVisible({ timeout: 5000 });
  await page.getByTestId("ui.ticker-picker.option-AAPL").click();
  await expect(page.getByTestId("stock.header.backtest")).toBeVisible({ timeout: 20000 });
  await page.getByTestId("stock.header.backtest").click();
  await expect(page.getByTestId("backtest.builder.weight-p1-AAPL")).toBeVisible({ timeout: 20000 });
});

test("backtest-results-depth: The results panel's depth controls: tabs, the rolling-window selector, and the log-scale switch, on a URL-seeded backtest.", async ({ page }) => {
  await page.goto("/");
  await page.goto("/backtest?p1=VTI:60,BND:40");
  await expect(page.getByTestId("backtest.results.export-csv")).toBeVisible({ timeout: 20000 });
  await page.getByTestId("backtest.results.tab-risk").click();
  await page.getByTestId("backtest.results.tab-rolling").click();
  await page.getByTestId("backtest.results.rolling-window-10").click();
  await page.getByTestId("backtest.results.tab-annual").click();
  await page.getByTestId("backtest.results.log-scale").click();
  await expect(page.getByTestId("backtest.results.export-csv")).toBeVisible({ timeout: 10000 });
});

test("xray-analyze-positions: X-ray end to end without auth: paste positions, analyze, reach the holdings panel, then reopen the collapsed inputs and switch to the activity tab.", async ({ page }) => {
  await page.goto("/xray");
  await expect(page.getByTestId("xray.inputs.positions")).toBeVisible({ timeout: 10000 });
  await page.getByTestId("xray.inputs.positions").fill("AAPL 12\nVTI 40");
  await page.getByTestId("xray.inputs.analyze-positions").click();
  await expect(page.getByTestId("xray.holdings.backtest-mix")).toBeVisible({ timeout: 30000 });
  await expect(page.getByTestId("xray.inputs.toggle")).toBeVisible({ timeout: 5000 });
  await page.getByTestId("xray.inputs.toggle").click();
  await page.getByTestId("xray.inputs.tab-activity").click();
  await expect(page.getByTestId("xray.inputs.activity")).toBeVisible({ timeout: 5000 });
});

test("not-found-recovery: A dead URL offers the way home, and home's tool cards render.", async ({ page }) => {
  await page.goto("/");
  await page.goto("/definitely-not-a-page");
  await expect(page.getByTestId("app.not-found.home")).toBeVisible({ timeout: 10000 });
  await page.getByTestId("app.not-found.home").click();
  await expect(page.getByTestId("landing.tools.card-backtest")).toBeVisible({ timeout: 10000 });
});
