// Generated by agent-handles from agent-handles/journey/v1 journeys. Do not edit;
// edit the journey manifest and recompile (npx agent-handles journeys compile).
import fs from "node:fs/promises";
import path from "node:path";
import { expect, test } from "@playwright/test";

const runtimeObserved = new Map<string, Set<string>>();
const pendingRuntimeReceipts = new Map<string, object>();
const runtimeRegistryPath = path.resolve(process.cwd(), "testid-registry.json");
type RuntimeRegistry = { entries?: Array<{ id: string }>; patterns?: Array<{ pattern: string }> };
let runtimeRegistryPromise: Promise<RuntimeRegistry> | undefined;

function loadRuntimeRegistry() {
  runtimeRegistryPromise ??= fs.readFile(runtimeRegistryPath, "utf8").then((text) => JSON.parse(text));
  return runtimeRegistryPromise;
}

function registryKnows(testId: string, registry: RuntimeRegistry) {
  if ((registry.entries ?? []).some((entry) => entry.id === testId)) return true;
  return (registry.patterns ?? []).some((entry) => entry.pattern.endsWith("*") && testId.startsWith(entry.pattern.slice(0, -1)));
}

test.afterAll(async () => {
  if (pendingRuntimeReceipts.size === 0) return;
  const directory = path.join(process.cwd(), ".agent-handles", "runtime-observations");
  await fs.mkdir(directory, { recursive: true });
  for (const [journeyName, receipt] of pendingRuntimeReceipts) {
    const file = journeyName.replace(/[^a-z0-9._-]+/gi, "-").replace(/^-+|-+$/g, "") || "journey";
    await fs.writeFile(path.join(directory, file + ".json"), JSON.stringify(receipt, null, 2) + "\n");
    runtimeObserved.delete(journeyName);
  }
  pendingRuntimeReceipts.clear();
});

async function captureRuntimeObservation(page: import("@playwright/test").Page) {
  let lastError: unknown;
  for (let attempt = 1; attempt <= 3; attempt += 1) {
    try {
      return await page.evaluate(async () => {
        await new Promise<void>((resolve) => requestAnimationFrame(() => requestAnimationFrame(() => resolve())));
        const RUNTIME_INTERACTIVE_SELECTOR =
          "button,input,select,textarea,a[href],summary,[contenteditable]:not([contenteditable='false']),[role='button'],[role='checkbox'],[role='combobox'],[role='link'],[role='menuitem'],[role='menuitemcheckbox'],[role='menuitemradio'],[role='option'],[role='radio'],[role='slider'],[role='spinbutton'],[role='switch'],[role='tab'],[role='textbox'],[role='treeitem'],[tabindex]:not([tabindex='-1'])";
        function isRuntimeObservationCandidate(element: Element) {
          if (element.closest("[data-agent-handles-overlay]")) return false;
          if (element.closest('[aria-hidden="true"]')) return false;
          const role = element.getAttribute?.("role");
          const nativeControl = element.matches?.('button,input,select,textarea,a[href],summary,[contenteditable]:not([contenteditable="false"])');
          if ((role === "tablist" || role === "tabpanel") && !nativeControl) return false;
          const style = window.getComputedStyle(element);
          const rect = element.getBoundingClientRect();
          return style.display !== "none" && style.visibility !== "hidden" && rect.width > 0 && rect.height > 0;
        }
        const controls = Array.from(document.querySelectorAll(RUNTIME_INTERACTIVE_SELECTOR))
          .filter(isRuntimeObservationCandidate)
          .map((element) => ({
            testId: element.getAttribute("data-testid"),
            tag: element.tagName.toLowerCase(),
            role: element.getAttribute("role"),
            text: (element.textContent ?? "").trim().replace(/\s+/g, " ").slice(0, 120),
          }));
        const allIds = Array.from(document.querySelectorAll("[data-testid]"))
          .filter(isRuntimeObservationCandidate)
          .map((element) => element.getAttribute("data-testid"))
          .filter((value): value is string => Boolean(value));
        const duplicateTestIds = [...new Set(allIds.filter((value, index) => allIds.indexOf(value) !== index))].sort();
        return {
          url: location.href,
          controls,
          unidentified: controls.filter((control) => !control.testId),
          duplicateTestIds,
        };
      });
    } catch (error) {
      lastError = error;
      const navigationRace = /execution context was destroyed|most likely because of a navigation/iu.test(String(error));
      if (!navigationRace || attempt === 3) throw error;
      await page.waitForLoadState("domcontentloaded");
    }
  }
  throw lastError;
}

async function reconcileRuntime(page: import("@playwright/test").Page, journeyName: string, step: number) {
  const observation = await captureRuntimeObservation(page);
  const registry = await loadRuntimeRegistry();
  const unknownTestIds = observation.controls.filter((control) => control.testId && !registryKnows(control.testId, registry));
  const observed = runtimeObserved.get(journeyName) ?? new Set<string>();
  for (const control of observation.controls) if (control.testId) observed.add(control.testId);
  runtimeObserved.set(journeyName, observed);
  const receipt = {
    schema: "agent-handles/runtime-journey-observation/v1",
    measuredAt: new Date().toISOString(),
    journeyName,
    lastStep: step,
    pageUrl: observation.url,
    observedTestIds: [...observed].sort(),
    unidentified: observation.unidentified,
    unknownTestIds,
    duplicateTestIds: observation.duplicateTestIds,
    statement:
      [...observed].length +
      " controls observed during this journey; runtime evidence is path-bound, and unvisited states remain uncovered.",
  };
  pendingRuntimeReceipts.set(journeyName, receipt);
  expect(observation.unidentified, "visible interactive controls without data-testid after step " + step).toEqual([]);
  expect(unknownTestIds, "visible controls with identity values absent from the registry after step " + step).toEqual([]);
  expect(observation.duplicateTestIds, "duplicate visible data-testid values after step " + step).toEqual([]);
}

async function recordFinalPageState(page: import("@playwright/test").Page, journeyName: string) {
  const observation = await captureRuntimeObservation(page);
  const registry = await loadRuntimeRegistry();
  const unknownTestIds = observation.controls.filter((control) => control.testId && !registryKnows(control.testId, registry));
  const directory = path.join(process.cwd(), ".agent-handles", "visual-reviews");
  const file = journeyName.replace(/[^a-z0-9._-]+/gi, "-").replace(/^-+|-+$/g, "") || "journey";
  const screenshotPath = path.join(directory, "journey-" + file + ".png");
  await fs.mkdir(directory, { recursive: true });
  await page.screenshot({ path: screenshotPath, fullPage: true });
  const observedTestIds = [...new Set(observation.controls.map((control) => control.testId).filter(Boolean))].sort();
  const receipt = {
    schema: "agent-handles/page-state-review/v1",
    id: "journey-" + file,
    measuredAt: new Date().toISOString(),
    route: new URL(observation.url).pathname + new URL(observation.url).search,
    label: journeyName + " final state",
    title: await page.title(),
    evidenceKind: "compiled-journey-final",
    journeyName,
    visibleControls: observation.controls.length,
    identifiedControls: observation.controls.filter((control) => control.testId).length,
    issues: {
      unidentified: observation.unidentified.length,
      unknown: unknownTestIds.length,
      duplicate: observation.duplicateTestIds.length,
      reviewRequired: 0,
    },
    observedTestIds,
    screenshot: path.relative(process.cwd(), screenshotPath).replaceAll(path.sep, "/"),
    statement:
      observation.controls.length +
      " controls observed in the final state of " +
      journeyName +
      "; this is page/state evidence, and unvisited states remain uncovered.",
  };
  await fs.writeFile(path.join(directory, "journey-" + file + ".json"), JSON.stringify(receipt, null, 2) + "\n");
}

test("backtest-advanced-disclosure: The backtest builder's Advanced toggle is present and enabled.", async ({ page }) => {
  await page.goto("/backtest");
  await expect(page.getByTestId("backtest.builder.advanced-toggle")).toBeVisible({ timeout: 10000 });
  await reconcileRuntime(page, "backtest-advanced-disclosure", 1);
  await expect(page.getByTestId("backtest.builder.advanced-toggle")).toBeEnabled();
  await reconcileRuntime(page, "backtest-advanced-disclosure", 2);
  await recordFinalPageState(page, "backtest-advanced-disclosure");
});

test("allocation-advanced-disclosure: The allocation builder's Advanced section is reachable through its stable id.", async ({ page }) => {
  await page.goto("/allocation");
  await expect(page.getByTestId("allocation.builder.advanced-toggle")).toBeVisible({ timeout: 10000 });
  await reconcileRuntime(page, "allocation-advanced-disclosure", 1);
  await page.getByTestId("allocation.builder.advanced-toggle").click();
  await reconcileRuntime(page, "allocation-advanced-disclosure", 2);
  await recordFinalPageState(page, "allocation-advanced-disclosure");
});

test("xray-positions-entry: Portfolio X-ray accepts pasted positions through the identified inputs.", async ({ page }) => {
  await page.goto("/xray");
  await expect(page.getByTestId("xray.inputs.positions")).toBeVisible({ timeout: 10000 });
  await reconcileRuntime(page, "xray-positions-entry", 1);
  await page.getByTestId("xray.inputs.positions").fill("AAPL 12\nVTI 40");
  await reconcileRuntime(page, "xray-positions-entry", 2);
  await expect(page.getByTestId("xray.inputs.positions")).toBeEnabled();
  await reconcileRuntime(page, "xray-positions-entry", 3);
  await recordFinalPageState(page, "xray-positions-entry");
});

test("backtest-builder-control-path: Build AMZN/GOOGL 60/40 vs SPY/QQQ through the controls alone: letter-by-letter ticker entry, keyboard selection, weight edits, the Radix rebalance dropdown, and the reinvest switch, ending with results rendered. Recorded live 2026-08-25 (27/27 receipts ok); the predicate v2 acceptance journey.", async ({
  page,
}) => {
  await page.goto("/");
  await page.getByTestId("app.nav.backtest").click();
  await reconcileRuntime(page, "backtest-builder-control-path", 1);
  await page.getByTestId("backtest.builder.picker-p1").pressSequentially("AMZN");
  await reconcileRuntime(page, "backtest-builder-control-path", 2);
  await page.getByTestId("backtest.builder.picker-p1").press("Enter");
  await reconcileRuntime(page, "backtest-builder-control-path", 3);
  await page.getByTestId("backtest.builder.picker-p1").pressSequentially("GOOGL");
  await reconcileRuntime(page, "backtest-builder-control-path", 4);
  await page.getByTestId("backtest.builder.picker-p1").press("Enter");
  await reconcileRuntime(page, "backtest-builder-control-path", 5);
  await page.getByTestId("backtest.builder.weight-p1-AMZN").fill("60");
  await reconcileRuntime(page, "backtest-builder-control-path", 6);
  await page.getByTestId("backtest.builder.weight-p1-GOOGL").fill("40");
  await reconcileRuntime(page, "backtest-builder-control-path", 7);
  await page.getByTestId("backtest.builder.add-portfolio").click();
  await reconcileRuntime(page, "backtest-builder-control-path", 8);
  await page.getByTestId("backtest.builder.picker-p2").pressSequentially("SPY");
  await reconcileRuntime(page, "backtest-builder-control-path", 9);
  await page.getByTestId("backtest.builder.picker-p2").press("Enter");
  await reconcileRuntime(page, "backtest-builder-control-path", 10);
  await page.getByTestId("backtest.builder.picker-p2").pressSequentially("QQQ");
  await reconcileRuntime(page, "backtest-builder-control-path", 11);
  await page.getByTestId("backtest.builder.picker-p2").press("Enter");
  await reconcileRuntime(page, "backtest-builder-control-path", 12);
  await expect(page.getByTestId("backtest.results.export-csv")).toBeVisible({ timeout: 20000 });
  await reconcileRuntime(page, "backtest-builder-control-path", 13);
  await page.getByTestId("backtest.builder.advanced-toggle").click();
  await reconcileRuntime(page, "backtest-builder-control-path", 14);
  await page.getByTestId("backtest.builder.rebalance-trigger").click();
  await reconcileRuntime(page, "backtest-builder-control-path", 15);
  await page.getByTestId("backtest.builder.rebalance-quarterly").click();
  await reconcileRuntime(page, "backtest-builder-control-path", 16);
  await expect(page.getByTestId("backtest.builder.rebalance-trigger")).toContainText("Quarterly", { timeout: 5000 });
  await reconcileRuntime(page, "backtest-builder-control-path", 17);
  await expect(page.getByTestId("backtest.builder.reinvest-toggle")).toBeChecked();
  await reconcileRuntime(page, "backtest-builder-control-path", 18);
  await page.getByTestId("backtest.builder.reinvest-toggle").click();
  await reconcileRuntime(page, "backtest-builder-control-path", 19);
  await expect(page.getByTestId("backtest.builder.reinvest-toggle")).not.toBeChecked({ timeout: 5000 });
  await reconcileRuntime(page, "backtest-builder-control-path", 20);
  await page.getByTestId("backtest.builder.reinvest-toggle").click();
  await reconcileRuntime(page, "backtest-builder-control-path", 21);
  await expect(page.getByTestId("backtest.builder.reinvest-toggle")).toBeChecked({ timeout: 5000 });
  await reconcileRuntime(page, "backtest-builder-control-path", 22);
  await expect(page.getByTestId("backtest.results.export-csv")).toBeVisible({ timeout: 20000 });
  await reconcileRuntime(page, "backtest-builder-control-path", 23);
  await recordFinalPageState(page, "backtest-builder-control-path");
});

test("research-ticker-drill: Nav to Research, find TXRH letter by letter, open it, then switch to AAPL through the header control. Recorded live 2026-08-25 (10/10 receipts ok), the first zero-navigate journey.", async ({
  page,
}) => {
  await page.goto("/");
  await page.getByTestId("app.nav.stock").click();
  await reconcileRuntime(page, "research-ticker-drill", 1);
  await page.getByTestId("ui.ticker-picker.search").pressSequentially("TXRH");
  await reconcileRuntime(page, "research-ticker-drill", 2);
  await expect(page.getByTestId("ui.ticker-picker.option-TXRH")).toBeVisible({ timeout: 5000 });
  await reconcileRuntime(page, "research-ticker-drill", 3);
  await page.getByTestId("ui.ticker-picker.option-TXRH").click();
  await reconcileRuntime(page, "research-ticker-drill", 4);
  await expect(page.getByTestId("stock.header.switch-ticker")).toBeVisible({ timeout: 20000 });
  await reconcileRuntime(page, "research-ticker-drill", 5);
  await expect(page.getByTestId("stock.header.switch-ticker")).toContainText("TXRH");
  await reconcileRuntime(page, "research-ticker-drill", 6);
  await page.getByTestId("stock.header.switch-ticker").click();
  await reconcileRuntime(page, "research-ticker-drill", 7);
  await page.getByTestId("ui.ticker-picker.search").pressSequentially("AAPL");
  await reconcileRuntime(page, "research-ticker-drill", 8);
  await expect(page.getByTestId("ui.ticker-picker.option-AAPL")).toBeVisible({ timeout: 5000 });
  await reconcileRuntime(page, "research-ticker-drill", 9);
  await page.getByTestId("ui.ticker-picker.option-AAPL").click();
  await reconcileRuntime(page, "research-ticker-drill", 10);
  await expect(page.getByTestId("stock.header.switch-ticker")).toContainText("AAPL", { timeout: 20000 });
  await reconcileRuntime(page, "research-ticker-drill", 11);
  await recordFinalPageState(page, "research-ticker-drill");
});

test("landing-cards: The landing page's tool cards are real entrances: the Monte Carlo card lands on the plan inputs.", async ({
  page,
}) => {
  await page.goto("/");
  await expect(page.getByTestId("landing.tools.card-backtest")).toBeVisible({ timeout: 10000 });
  await reconcileRuntime(page, "landing-cards", 1);
  await page.getByTestId("landing.tools.card-montecarlo").click();
  await reconcileRuntime(page, "landing-cards", 2);
  await expect(page.getByTestId("montecarlo.plan.starting-balance")).toBeVisible({ timeout: 10000 });
  await reconcileRuntime(page, "landing-cards", 3);
  await recordFinalPageState(page, "landing-cards");
});

test("montecarlo-plan-control-path: Retirement plan edited through the controls: balance, horizon, and the simulation method dropdown.", async ({
  page,
}) => {
  await page.goto("/");
  await page.getByTestId("app.nav.montecarlo").click();
  await reconcileRuntime(page, "montecarlo-plan-control-path", 1);
  await page.getByTestId("montecarlo.plan.starting-balance").fill("750000");
  await reconcileRuntime(page, "montecarlo-plan-control-path", 2);
  await page.getByTestId("montecarlo.plan.years-to-retire").fill("10");
  await reconcileRuntime(page, "montecarlo-plan-control-path", 3);
  await page.getByTestId("montecarlo.plan.horizon").fill("40");
  await reconcileRuntime(page, "montecarlo-plan-control-path", 4);
  await page.getByTestId("montecarlo.plan.method-trigger").click();
  await reconcileRuntime(page, "montecarlo-plan-control-path", 5);
  await page.getByTestId("montecarlo.plan.method-bootstrap").click();
  await reconcileRuntime(page, "montecarlo-plan-control-path", 6);
  await expect(page.getByTestId("montecarlo.plan.method-trigger")).toContainText("Bootstrap", { timeout: 5000 });
  await reconcileRuntime(page, "montecarlo-plan-control-path", 7);
  await recordFinalPageState(page, "montecarlo-plan-control-path");
});

test("allocation-builder-control-path: Allocation built through the controls: asset picked from the autocomplete, weights edited, a comparison portfolio added, dates set through the date picker, inflation toggled.", async ({
  page,
}) => {
  await page.goto("/");
  await page.getByTestId("app.nav.allocation").click();
  await reconcileRuntime(page, "allocation-builder-control-path", 1);
  await page.getByTestId("allocation.builder.picker-p1").pressSequentially("small");
  await reconcileRuntime(page, "allocation-builder-control-path", 2);
  await expect(page.getByTestId("allocation.asset-picker.option-smallCap")).toBeVisible({ timeout: 5000 });
  await reconcileRuntime(page, "allocation-builder-control-path", 3);
  await page.getByTestId("allocation.asset-picker.option-smallCap").click();
  await reconcileRuntime(page, "allocation-builder-control-path", 4);
  await expect(page.getByTestId("allocation.builder.weight-p1-smallCap")).toBeVisible({ timeout: 10000 });
  await reconcileRuntime(page, "allocation-builder-control-path", 5);
  await page.getByTestId("allocation.builder.add-portfolio").click();
  await reconcileRuntime(page, "allocation-builder-control-path", 6);
  await page.getByTestId("ui.date-picker.input-alloc-start").fill("01/01/1990");
  await reconcileRuntime(page, "allocation-builder-control-path", 7);
  await page.getByTestId("ui.date-picker.input-alloc-start").press("Enter");
  await reconcileRuntime(page, "allocation-builder-control-path", 8);
  await expect(page.getByTestId("ui.date-picker.clear-alloc-start")).toBeVisible({ timeout: 5000 });
  await reconcileRuntime(page, "allocation-builder-control-path", 9);
  await page.getByTestId("allocation.builder.inflation-toggle").click();
  await reconcileRuntime(page, "allocation-builder-control-path", 10);
  await expect(page.getByTestId("allocation.builder.inflation-toggle")).toBeChecked({ timeout: 5000 });
  await reconcileRuntime(page, "allocation-builder-control-path", 11);
  await recordFinalPageState(page, "allocation-builder-control-path");
});

test("income-sample-portfolio: The dividend planner's one-tap sample loads SCHD/VYM/JEPI; total value and per-holding weights stay editable.", async ({
  page,
}) => {
  await page.goto("/");
  await page.getByTestId("app.nav.income").click();
  await reconcileRuntime(page, "income-sample-portfolio", 1);
  await page.getByTestId("income.setup.load-sample").click();
  await reconcileRuntime(page, "income-sample-portfolio", 2);
  await expect(page.getByTestId("income.setup.weight-SCHD")).toBeVisible({ timeout: 20000 });
  await reconcileRuntime(page, "income-sample-portfolio", 3);
  await page.getByTestId("income.setup.total-value").fill("250000");
  await reconcileRuntime(page, "income-sample-portfolio", 4);
  await page.getByTestId("income.setup.weight-SCHD").fill("50");
  await reconcileRuntime(page, "income-sample-portfolio", 5);
  await expect(page.getByTestId("income.setup.weight-JEPI")).toBeVisible();
  await reconcileRuntime(page, "income-sample-portfolio", 6);
  await recordFinalPageState(page, "income-sample-portfolio");
});

test("stock-to-backtest-crossover: Cross-page control path: research AAPL, then the stock header's Backtest button seeds the backtest builder with AAPL at 100.", async ({
  page,
}) => {
  await page.goto("/");
  await page.getByTestId("app.nav.stock").click();
  await reconcileRuntime(page, "stock-to-backtest-crossover", 1);
  await page.getByTestId("ui.ticker-picker.search").pressSequentially("AAPL");
  await reconcileRuntime(page, "stock-to-backtest-crossover", 2);
  await expect(page.getByTestId("ui.ticker-picker.option-AAPL")).toBeVisible({ timeout: 5000 });
  await reconcileRuntime(page, "stock-to-backtest-crossover", 3);
  await page.getByTestId("ui.ticker-picker.option-AAPL").click();
  await reconcileRuntime(page, "stock-to-backtest-crossover", 4);
  await expect(page.getByTestId("stock.header.backtest")).toBeVisible({ timeout: 20000 });
  await reconcileRuntime(page, "stock-to-backtest-crossover", 5);
  await page.getByTestId("stock.header.backtest").click();
  await reconcileRuntime(page, "stock-to-backtest-crossover", 6);
  await expect(page.getByTestId("backtest.builder.weight-p1-AAPL")).toBeVisible({ timeout: 20000 });
  await reconcileRuntime(page, "stock-to-backtest-crossover", 7);
  await recordFinalPageState(page, "stock-to-backtest-crossover");
});

test("backtest-results-depth: The results panel's depth controls: tabs, the rolling-window selector, and the log-scale switch, on a URL-seeded backtest.", async ({
  page,
}) => {
  await page.goto("/");
  await page.goto("/backtest?p1=VTI:60,BND:40");
  await reconcileRuntime(page, "backtest-results-depth", 1);
  await expect(page.getByTestId("backtest.results.export-csv")).toBeVisible({ timeout: 20000 });
  await reconcileRuntime(page, "backtest-results-depth", 2);
  await page.getByTestId("backtest.results.tab-risk").click();
  await reconcileRuntime(page, "backtest-results-depth", 3);
  await page.getByTestId("backtest.results.tab-rolling").click();
  await reconcileRuntime(page, "backtest-results-depth", 4);
  await page.getByTestId("backtest.results.rolling-window-10").click();
  await reconcileRuntime(page, "backtest-results-depth", 5);
  await page.getByTestId("backtest.results.tab-annual").click();
  await reconcileRuntime(page, "backtest-results-depth", 6);
  await page.getByTestId("backtest.results.log-scale").click();
  await reconcileRuntime(page, "backtest-results-depth", 7);
  await expect(page.getByTestId("backtest.results.export-csv")).toBeVisible({ timeout: 10000 });
  await reconcileRuntime(page, "backtest-results-depth", 8);
  await recordFinalPageState(page, "backtest-results-depth");
});

test("xray-analyze-positions: X-ray end to end without auth: paste positions, analyze, reach the holdings panel, then reopen the collapsed inputs and switch to the activity tab.", async ({
  page,
}) => {
  await page.goto("/xray");
  await expect(page.getByTestId("xray.inputs.positions")).toBeVisible({ timeout: 10000 });
  await reconcileRuntime(page, "xray-analyze-positions", 1);
  await page.getByTestId("xray.inputs.positions").fill("AAPL 12\nVTI 40");
  await reconcileRuntime(page, "xray-analyze-positions", 2);
  await page.getByTestId("xray.inputs.analyze-positions").click();
  await reconcileRuntime(page, "xray-analyze-positions", 3);
  await expect(page.getByTestId("xray.holdings.backtest-mix")).toBeVisible({ timeout: 30000 });
  await reconcileRuntime(page, "xray-analyze-positions", 4);
  await expect(page.getByTestId("xray.inputs.toggle")).toBeVisible({ timeout: 5000 });
  await reconcileRuntime(page, "xray-analyze-positions", 5);
  await page.getByTestId("xray.inputs.toggle").click();
  await reconcileRuntime(page, "xray-analyze-positions", 6);
  await page.getByTestId("xray.inputs.tab-activity").click();
  await reconcileRuntime(page, "xray-analyze-positions", 7);
  await expect(page.getByTestId("xray.inputs.activity")).toBeVisible({ timeout: 5000 });
  await reconcileRuntime(page, "xray-analyze-positions", 8);
  await recordFinalPageState(page, "xray-analyze-positions");
});

test("not-found-recovery: A dead URL offers the way home, and home's tool cards render.", async ({ page }) => {
  await page.goto("/");
  await page.goto("/definitely-not-a-page");
  await reconcileRuntime(page, "not-found-recovery", 1);
  await expect(page.getByTestId("app.not-found.home")).toBeVisible({ timeout: 10000 });
  await reconcileRuntime(page, "not-found-recovery", 2);
  await page.getByTestId("app.not-found.home").click();
  await reconcileRuntime(page, "not-found-recovery", 3);
  await expect(page.getByTestId("landing.tools.card-backtest")).toBeVisible({ timeout: 10000 });
  await reconcileRuntime(page, "not-found-recovery", 4);
  await recordFinalPageState(page, "not-found-recovery");
});
